#pragma once

typedef enum {
  ENTITY_TYPE_NONE,
  ENTITY_TYPE_PLAYER,
  ENTITY_TYPE_ENEMY,
  ENTITY_TYPE_SOULSHARD,
  ENTITY_TYPE_KNIFE,
  ENTITY_TYPE_ITEM,
  ENTITY_TYPE_PARTICLE,
  ENTITY_TYPE_GENERATOR,
  ENTITY_TYPE_COUNT
} entity_type;
