#pragma once

typedef enum {
  POWERUP_TYPE_KNIFE_LARGENESS,
  POWERUP_TYPE_KNIFE_COOLDOWN,
  POWERUP_TYPE_KNIFE_QUANTITY,
  POWERUP_TYPE_KNIFE_SPEED,
  POWERUP_TYPE_KNIFE_SPRAY,
  POWERUP_TYPE_HEART,
  POWERUP_TYPE_MAGNETISM_THRESHOLD,
  POWERUP_TYPE_SKULL_SPEED,
  POWERUP_TYPE_COUNT
} powerup_type;
